Steal stock fill color
Luki120/LinearRevamped pull request #1
Opened 2022-03-01 20:05 UTC by WilsontheWolf

This PR is a draft because I haven't changed the swift code. Couldn't get it to run properly so you'll have to do it, or get it fixed for me.

This PR steals the fill color from the stock battery. Doing so fixes the following
- iPad's use the proper percentage for low power (10% instead of 20%)
- Compatibility with Eliza (and other tweaks that change battery color)
- Will ensure compatibility if iOS adds a new battery color.

This also greatly reduces code due to the following:
- Storage of LPM and charging state is now unnecessary, as such they have been removed and any code related to getting them has been removed.
- Code related to updating the color has been removed, because iOS tells us when to update the color.
- Code relating to figuring out the color has been removed because iOS does that for us.
- References to colors to use is removed.

I've also fixed a bug I encountered when the iPad's "Not Charging" text would not go away, by setting the prercent string check to set the value to "" instead of just ignoring it.

2022-03-02 01:50 UTC, Luki120 requested changes

2022-03-02 01:50 UTC, Luki120 commented on Objective-C/Tweak.m
> +static UIColor* (*origBatteryFillColor)(_UIBatteryView *self, SEL _cmd);
For consistency

```suggestion
static UIColor *(*origBFC)(_UIBatteryView *self, SEL _cmd);
```

2022-03-02 01:50 UTC, Luki120 commented on Objective-C/Tweak.m
> +	MSHookMessageEx(kClass(@"_UIBatteryView"), @selector(_batteryFillColor), (IMP) &overrideBFC, (IMP *) &origBatteryFillColor);
```suggestion
MSHookMessageEx(kClass(@"_UIBatteryView"), @selector(_batteryFillColor), (IMP) &overrideBFC, (IMP *) &origBFC);
```

2022-03-02 01:51 UTC, Luki120 requested changes

2022-03-02 01:51 UTC, Luki120 commented on Objective-C/Tweak.m
> +	stockColor = origBatteryFillColor(self, _cmd);
```suggestion
stockColor =  origBFC(self, _cmd);
```

2022-03-02 02:56 UTC, Luki120 approved these changes

2022-03-02 02:58 UTC, Luki120 commented
Looks good, can't merge right now since I added a bolt view to show when the device is charging, so the user can be aware of that if they are in LPM, you'll probably have to resolve merge conflicts after I push those changes, sorry

2022-03-15 23:25 UTC, Luki120 commented
Hey, I've implemented your changes for the Swift version here https://github.com/Luki120/LinearRevamped/commit/3502ae7fa5979a22ab91df75d96c069ee9e259b4 and it's working good. I've updated the objc version as well with the changes I had locally so would you mind fixing merge conflicts 🙏🏽. You'll want to re add the hook where I get the battery state though, since it's needed to know when the bolt needs to animate or not. You can use the property as well if you wish, whatever works.

2022-03-15 23:26 UTC, WilsontheWolf commented
Thanks I'll take a look

2022-03-15 23:47 UTC, WilsontheWolf commented
Ok I've updated the code

2022-03-16 01:25 UTC, Luki120 approved these changes

2022-03-16 01:25 UTC, Luki120 commented
Thanks

2022-03-16 01:26 UTC, merged